
def writeCords(file,df,frame_no):
  atoms=df.shape[0]
  file.write(str(atoms)+'\n')
  file.write('frame {} XYZ file generated by PYTHON code : coordinates in Angstrom\n'.format(frame_no))
  for i in range(atoms):
    row=df.iloc[i,:]
    line=row['atom']+'  '+ \
        str(row['x'])+'  '+ \
        str(row['y'])+'  '+ \
        str(row['z'])+'\n'
    file.write(line)
  
